import fs from 'fs';
import path from 'path';

const svgContent = fs.readFileSync('africa.svg', 'utf8');

// Regex to find paths and their names
const pathRegex = /<path\s+id="([^"]+)"\s+d="([^"]+)"[\s\S]*?<name>([^<]+)<\/name>[\s\S]*?<\/path>/g;

const countries = [];
let match;
while ((match = pathRegex.exec(svgContent)) !== null) {
  countries.push({
    id: match[1].toUpperCase(),
    path: match[2],
    name: match[3]
  });
}

console.log(`Found ${countries.length} countries.`);

const outputPath = path.join('src', 'components', 'AfricaMapData.ts');

const tsContent = `// This file is auto-generated by parse_svg.js. Do not edit directly.
export interface CountryPath {
  id: string;
  name: string;
  path: string;
}

export const AFRICA_COUNTRIES: CountryPath[] = ${JSON.stringify(countries, null, 2)};
`;

fs.writeFileSync(outputPath, tsContent, 'utf8');
console.log(`Wrote map data to ${outputPath}`);
